



{
	"_RejCode":"000000",
    "RecordNumber":"50",
    "PageSize":"1",
    "CurrentIndex":"1",
    "List":
        [
            {
                "SupplyerId":"123456",
                "SupplyerIndex":"3",
                "SupplyerName":"北京烤鸭",
                "Addr":"体育路16号",
                "City":"辽宁营口",
                "CityShop":"营口商圈",
                "Classification":"旅行分类",
                "SupplyerLat":"40.656537",
                "SupplyerLon":"122.228463",
                "Opentime":"10：00-22：00",
                "StartDate":"2012-05-01",
                "EndDate":"2014-05-01",
                "Consumption":"50",
                "Parkingspace":"YES",
                "Transportation":"交通指南哦，测试用的，哈哈哈，体育路16号，北京朝阳区。",
                "Content":"图片.jpg",
                "Introduction":"这是商户介绍，朋友聚餐,家庭聚会,休闲时光,大型宴会,情侣约会,免费停车,随便吃吃,是老字号,可以刷卡,休闲小憩,无线上网。",
                "Branch":"营口银行",
                "Information":"刷营口银行卡可享受9.5折",
                "CardBin":"辽河卡、白净卡、营口银行卡",
                "Phone":"0417-0035017"
            }
            ,
            {
                 "SupplyerId":"123456676",
                "SupplyerIndex":"5",
                "SupplyerName":"营口旅游",
                "Addr":"体育路17号",
                "City":"辽宁营口",
                "CityShop":"营口商圈",
                "Classification":"旅行分类",
                "SupplyerLat":"40.656537",
                "SupplyerLon":"122.228463",
                "Opentime":"10：00-22：00",
                "StartDate":"2012-05-01",
                "EndDate":"2014-05-01",
                "Consumption":"250",
                "Parkingspace":"NO",
                "Transportation":"交通指南哦，测试用的，哈哈哈，体育路16号，辽宁朝阳区。",
                "Content":"图片.jpg",
                "Introduction":"这是商户介绍，朋友聚餐,家庭聚会,休闲时光,大型宴会,情侣约会,免费停车,随便吃吃,是老字号,可以刷卡,休闲小憩,无线上网。",
                "Branch":"营口银行",
                "Information":"营口银行卡9折,辽河卡8.88折啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊",
                "CardBin":"辽河卡、白净卡、营口银行卡",
                "Phone":"0417-0035016"
            }
        ]
}